using System;
using System.Collections.Generic;

namespace Video_Platform_Backend.Models;

public partial class VideoThumbnail
{
    public Guid Id { get; set; }

    public Guid VideoId { get; set; }

    public string ThumbnailUrl { get; set; } = null!;

    public bool? IsAutoGenerated { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Video Video { get; set; } = null!;
}
