-- =========================================
-- VIDEO SHARING PLATFORM - FULL DATABASE SCHEMA
-- =========================================

CREATE DATABASE VideoPlatformDB;
GO

USE VideoPlatformDB;
GO

-- =========================================
-- 1. USERS & ACCOUNTS
-- =========================================
CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255), -- Có thể null nếu đăng nhập qua Google/FB
    GoogleId NVARCHAR(255),
    FacebookId NVARCHAR(255),
    IsEmailVerified BIT DEFAULT 0,
    IsPhoneVerified BIT DEFAULT 0,
    PhoneNumber NVARCHAR(20),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    IsActive BIT DEFAULT 1,
    IsBanned BIT DEFAULT 0,
    Role NVARCHAR(20) DEFAULT 'User' -- User, Moderator, Admin
);
GO

CREATE TABLE Profiles (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    FullName NVARCHAR(150),
    AvatarUrl NVARCHAR(500),
    CoverUrl NVARCHAR(500),
    Bio NVARCHAR(1000),
    DateOfBirth DATE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
GO

CREATE TABLE Channels (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    ChannelName NVARCHAR(100) NOT NULL UNIQUE,
    Handle NVARCHAR(50) NOT NULL UNIQUE,
    Description NVARCHAR(MAX),
    BannerUrl NVARCHAR(500),
    SocialLinks NVARCHAR(MAX), -- JSON string
    TotalViews BIGINT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
GO

CREATE TABLE Settings (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    Theme NVARCHAR(20) DEFAULT 'System', -- Light, Dark, System
    Language NVARCHAR(20) DEFAULT 'Vietnamese',
    PrivacySettings NVARCHAR(MAX), -- JSON (Who can comment, message...)
    NotificationSettings NVARCHAR(MAX), -- JSON (Push, Email...)
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
GO

-- =========================================
-- 2. VIDEOS & MEDIA
-- =========================================
CREATE TABLE VideoCategories (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    Description NVARCHAR(255)
);
GO

CREATE TABLE Videos (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ChannelId UNIQUEIDENTIFIER NOT NULL,
    CategoryId INT,
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX),
    Visibility NVARCHAR(20) DEFAULT 'Public', -- Public, Private, Unlisted
    Duration INT, -- giây
    ViewsCount BIGINT DEFAULT 0,
    LikesCount INT DEFAULT 0,
    DislikesCount INT DEFAULT 0,
    CommentsCount INT DEFAULT 0,
    ScheduledAt DATETIME,
    IsShort BIT DEFAULT 0, -- 1 = Short video, 0 = Normal
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ChannelId) REFERENCES Channels(Id) ON DELETE CASCADE,
    FOREIGN KEY (CategoryId) REFERENCES VideoCategories(Id)
);
GO

CREATE TABLE VideoFiles (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    VideoId UNIQUEIDENTIFIER NOT NULL,
    Resolution NVARCHAR(20), -- 1080p, 720p, etc.
    FileUrl NVARCHAR(500) NOT NULL,
    FileSize BIGINT,
    Format NVARCHAR(20), -- MP4, HLS
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (VideoId) REFERENCES Videos(Id) ON DELETE CASCADE
);
GO

CREATE TABLE VideoThumbnails (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    VideoId UNIQUEIDENTIFIER NOT NULL,
    ThumbnailUrl NVARCHAR(500) NOT NULL,
    IsAutoGenerated BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (VideoId) REFERENCES Videos(Id) ON DELETE CASCADE
);
GO

CREATE TABLE VideoTags (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    VideoId UNIQUEIDENTIFIER NOT NULL,
    Tag NVARCHAR(50) NOT NULL,
    FOREIGN KEY (VideoId) REFERENCES Videos(Id) ON DELETE CASCADE
);
GO

-- =========================================
-- 3. INTERACTION & SOCIAL
-- =========================================
CREATE TABLE Likes (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    VideoId UNIQUEIDENTIFIER NOT NULL,
    IsLike BIT NOT NULL, -- 1=Like, 0=Dislike
    CreatedAt DATETIME DEFAULT GETDATE(),
    UNIQUE(UserId, VideoId),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (VideoId) REFERENCES Videos(Id)
);
GO

CREATE TABLE Comments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    VideoId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    LikesCount INT DEFAULT 0,
    IsPinned BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (VideoId) REFERENCES Videos(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE CommentReplies (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ParentCommentId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    LikesCount INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ParentCommentId) REFERENCES Comments(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE CommentLikes (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    CommentId UNIQUEIDENTIFIER NOT NULL,
    IsLike BIT NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UNIQUE(UserId, CommentId),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (CommentId) REFERENCES Comments(Id)
);
GO

CREATE TABLE Followers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FollowerId UNIQUEIDENTIFIER NOT NULL,
    ChannelId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UNIQUE(FollowerId, ChannelId),
    FOREIGN KEY (FollowerId) REFERENCES Users(Id),
    FOREIGN KEY (ChannelId) REFERENCES Channels(Id)
);
GO

-- =========================================
-- 4. PLAYLISTS & WATCH HISTORY
-- =========================================
CREATE TABLE Playlists (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ChannelId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(1000),
    Visibility NVARCHAR(20) DEFAULT 'Public',
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ChannelId) REFERENCES Channels(Id) ON DELETE CASCADE
);
GO

CREATE TABLE PlaylistVideos (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PlaylistId UNIQUEIDENTIFIER NOT NULL,
    VideoId UNIQUEIDENTIFIER NOT NULL,
    SortOrder INT DEFAULT 0,
    AddedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (PlaylistId) REFERENCES Playlists(Id) ON DELETE CASCADE,
    FOREIGN KEY (VideoId) REFERENCES Videos(Id)
);
GO

CREATE TABLE WatchHistories (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    VideoId UNIQUEIDENTIFIER NOT NULL,
    WatchedDuration INT, -- Thời gian đã xem tính bằng giây
    LastWatchedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (VideoId) REFERENCES Videos(Id) ON DELETE CASCADE
);
GO

CREATE TABLE Views (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    VideoId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NULL, -- Null nếu là guest
    IpAddress NVARCHAR(50),
    ViewedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (VideoId) REFERENCES Videos(Id) ON DELETE CASCADE
);
GO

-- =========================================
-- 5. MESSAGES & NOTIFICATIONS
-- =========================================
CREATE TABLE Conversations (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE ConversationParticipants (
    ConversationId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    JoinedAt DATETIME DEFAULT GETDATE(),
    PRIMARY KEY(ConversationId, UserId),
    FOREIGN KEY (ConversationId) REFERENCES Conversations(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE Messages (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER NOT NULL,
    SenderId UNIQUEIDENTIFIER NOT NULL,
    Content NVARCHAR(MAX),
    AttachmentUrl NVARCHAR(500),
    IsSeen BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ConversationId) REFERENCES Conversations(Id) ON DELETE CASCADE,
    FOREIGN KEY (SenderId) REFERENCES Users(Id)
);
GO

CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Type NVARCHAR(50) NOT NULL, -- Like, Comment, Subscribe, System
    Message NVARCHAR(MAX) NOT NULL,
    TargetUrl NVARCHAR(500),
    IsRead BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
GO

-- =========================================
-- 6. REPORT & MODERATION & COPYRIGHT
-- =========================================
CREATE TABLE Reports (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ReporterId UNIQUEIDENTIFIER NOT NULL,
    TargetId UNIQUEIDENTIFIER NOT NULL, -- Có thể là VideoId, CommentId, UserId
    TargetType NVARCHAR(50) NOT NULL, -- Video, Comment, User
    Reason NVARCHAR(100) NOT NULL, -- Spam, Violence...
    Description NVARCHAR(MAX),
    Status NVARCHAR(50) DEFAULT 'Pending', -- Pending, Resolved, Rejected
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ReporterId) REFERENCES Users(Id)
);
GO

CREATE TABLE CopyrightClaims (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    VideoId UNIQUEIDENTIFIER NOT NULL,
    ClaimantId UNIQUEIDENTIFIER NOT NULL,
    Reason NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(50) DEFAULT 'Pending',
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (VideoId) REFERENCES Videos(Id) ON DELETE CASCADE,
    FOREIGN KEY (ClaimantId) REFERENCES Users(Id)
);
GO

-- =========================================
-- 7. LIVESTREAM
-- =========================================
CREATE TABLE Livestreams (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ChannelId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    StreamKey NVARCHAR(255) NOT NULL UNIQUE,
    Status NVARCHAR(50) DEFAULT 'Scheduled', -- Scheduled, Live, Ended
    ScheduledStartTime DATETIME,
    ActualStartTime DATETIME,
    EndTime DATETIME,
    CurrentViewers INT DEFAULT 0,
    FOREIGN KEY (ChannelId) REFERENCES Channels(Id) ON DELETE CASCADE
);
GO

CREATE TABLE LiveMessages (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    LivestreamId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    SentAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (LivestreamId) REFERENCES Livestreams(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

-- =========================================
-- 8. MONETIZATION & PAYMENTS
-- =========================================
CREATE TABLE Subscriptions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SubscriberId UNIQUEIDENTIFIER NOT NULL,
    ChannelId UNIQUEIDENTIFIER NOT NULL,
    Tier NVARCHAR(50), -- Free, Premium
    Price DECIMAL(18,2) DEFAULT 0,
    StartDate DATETIME DEFAULT GETDATE(),
    EndDate DATETIME,
    Status NVARCHAR(50) DEFAULT 'Active',
    FOREIGN KEY (SubscriberId) REFERENCES Users(Id),
    FOREIGN KEY (ChannelId) REFERENCES Channels(Id)
);
GO

CREATE TABLE Payments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Currency NVARCHAR(10) DEFAULT 'VND',
    PaymentMethod NVARCHAR(50),
    Status NVARCHAR(50) DEFAULT 'Pending', -- Pending, Completed, Failed
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE Transactions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PaymentId UNIQUEIDENTIFIER NOT NULL,
    TransactionType NVARCHAR(50), -- Donation, Subscription, AdRevenue
    TargetChannelId UNIQUEIDENTIFIER,
    Amount DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (PaymentId) REFERENCES Payments(Id),
    FOREIGN KEY (TargetChannelId) REFERENCES Channels(Id)
);
GO
