USE VideoPlatformDB;
GO

-- Lấy UserID và ChannelID có sẵn (Lấy 1 channel bất kỳ trong hệ thống)
DECLARE @User1 UNIQUEIDENTIFIER = (SELECT TOP 1 UserId FROM Channels);
DECLARE @Channel1 UNIQUEIDENTIFIER = (SELECT TOP 1 Id FROM Channels WHERE UserId = @User1);
DECLARE @CatTech INT = (SELECT TOP 1 Id FROM VideoCategories);

IF @Channel1 IS NOT NULL
BEGIN
    DECLARE @Short1 UNIQUEIDENTIFIER = NEWID();
    DECLARE @Short2 UNIQUEIDENTIFIER = NEWID();
    DECLARE @Short3 UNIQUEIDENTIFIER = NEWID();
    DECLARE @Short4 UNIQUEIDENTIFIER = NEWID();
    DECLARE @Short5 UNIQUEIDENTIFIER = NEWID();

    -- Xóa các video ngắn cũ (bị lỗi font)
    DELETE FROM Videos WHERE IsShort = 1;

    -- Insert Videos (IsShort = 1)
    INSERT INTO Videos (Id, ChannelId, CategoryId, Title, Description, Visibility, Duration, ViewsCount, LikesCount, IsShort) VALUES
    (@Short1, @Channel1, @CatTech, N'🔥 Khoảnh khắc đẹp nhất trong ngày hôm nay #viral #trending', N'Một ngày tuyệt vời bắt đầu với những điều nhỏ bé 🌅', 'Public', 45, 128400, 3421, 1),
    (@Short2, @Channel1, @CatTech, N'🌊 Khám phá bãi biển đẹp nhất Việt Nam | Du lịch', N'Du lịch 2024 không thể bỏ lỡ 🏝️ #travel', 'Public', 30, 245000, 7800, 1),
    (@Short3, @Channel1, @CatTech, N'😂 Clip hài hước cười không nhặt được mồm!', N'Hài hước mỗi ngày giúp bạn sống vui hơn 🎉', 'Public', 55, 512000, 12300, 1),
    (@Short4, @Channel1, @CatTech, N'🍜 Review ẩm thực đường phố - Phở chuẩn vị', N'Không ăn thử thì tiếc lắm đó! 😋 #food', 'Public', 60, 334000, 9200, 1),
    (@Short5, @Channel1, @CatTech, N'💪 Bài tập 10 phút mỗi sáng giảm mỡ bụng', N'Kiên trì 30 ngày bạn sẽ thấy sự khác biệt 🔥 #gym', 'Public', 40, 456000, 11200, 1);

    -- Insert VideoFiles (Sử dụng URL video ngắn dạng đứng - dọc)
    INSERT INTO VideoFiles (Id, VideoId, Resolution, FileUrl, FileSize, Format) VALUES
    (NEWID(), @Short1, '1080p', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 15000000, 'MP4'),
    (NEWID(), @Short2, '1080p', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 18000000, 'MP4'),
    (NEWID(), @Short3, '1080p', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 12000000, 'MP4'),
    (NEWID(), @Short4, '1080p', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 20000000, 'MP4'),
    (NEWID(), @Short5, '1080p', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4', 14000000, 'MP4');

    -- Insert VideoThumbnails (Dùng ảnh dọc)
    INSERT INTO VideoThumbnails (Id, VideoId, ThumbnailUrl, IsAutoGenerated) VALUES
    (NEWID(), @Short1, 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=400&h=711&fit=crop', 0),
    (NEWID(), @Short2, 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=711&fit=crop', 0),
    (NEWID(), @Short3, 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=711&fit=crop', 0),
    (NEWID(), @Short4, 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=711&fit=crop', 0),
    (NEWID(), @Short5, 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400&h=711&fit=crop', 0);
    
    PRINT 'Đã chèn 5 Video Shorts mẫu thành công!';
END
ELSE
BEGIN
    PRINT 'Không tìm thấy Channel nào trong Database để chèn Shorts.';
END
GO
